### ISSUE TITLE
Was this project pushing the Docker image to any public registry?

### ISSUE THREAD

**Issue by mrnonz** [sap-contributions/prometheus-logstash-exporter#9]
Hello,

I hope all is well. I have a brief inquiry: Have you created and uploaded any Docker images to a public registry?

Thank you.

**Comment by LHozzan** [comment]
Hello.
Thank you for your interest.
Actually not. We not provide any Docker image accessible from public internet.
But if will be interest, I can open this topic in our team and lets see.
Best regards.

**Comment by mrnonz** [comment]
Cheer up to open this to public internet.

Thank you

**Comment by LHozzan** [comment]
@mrnonz Building Docker image was added, for details, please, see README.

**Comment by mrnonz** [comment]
@LHozzan Wow, thank you so much.
